[[credential.credentials]]
expired_date = ""

[[credential.credentials.claims]]
name = ""
value = ""

[credential.credentials.issuer]
name = ""

[credential.credentials.issuer.public_key]
x = ""
y = ""

[criteria]
combinations = ["", ""]
valid_date = ""

[[criteria.conditions]]
issuer = ""
name = ""
operator = ""
value = ""

[[criteria.conditions]]
issuer = ""
name = ""
operator = ""
value = ""

[[criteria.conditions]]
issuer = ""
name = ""
operator = ""
value = ""

[signature]
s = ""

[signature.r8]
x = ""
y = ""
