[[credential.credentials]]
expired_date = 5
issuer = "issuer00"

[[credential.credentials.claims]]
name = "birth_day  "
value = 19

[[credential.credentials.claims]]
name = "nationality"
value = 84

[[credential.credentials]]
expired_date = 11
issuer = "issuer01"

[[credential.credentials.claims]]
name = "birth_day  "
value = 19

[[credential.credentials.claims]]
name = "birth_day  "
value = 19

[criteria]
combinations = ["&", "|"]
valid_date = 5

[[criteria.conditions]]
issuer = "issuer00"
name = "birth_day  "
operator = "> "
value = 18

[[criteria.conditions]]
issuer = "issuer01"
name = "birth_day  "
operator = "> "
value = 18

[[criteria.conditions]]
issuer = "issuer00"
name = "nationality"
operator = "=="
value = 84