[package]
name = "state_transition"
type = "bin"
authors = [""]
compiler_version = ">=0.23.0"

[dependencies]
# smt = { path = "../libs/smt_bn254" }
smt = { tag = "v0.1.0", git = "https://github.com/privacy-scaling-explorations/zk-kit/packages/circuits/noir", directory="crates/smt_bn254" }