[package]
name = "nested_vcp_generation"
type = "bin"
authors = ["Tu Hoang"]
compiler_version = ">=0.23.0"

[dependencies]
smt = { path="../libs/smtverifier_noir" }
zkvc = { path="../libs/zkvc_utils" }