[package]
name = "vcp_generation"
type = "bin"
authors = ["Tu Hoang"]
compiler_version = ">=0.19.4"

[dependencies]
smt = { path="../libs/smtverifier_noir" }
zkvc = { path="../libs/zkvc_utils" }
settings = { path="../libs/zkvc_settings" }